[project]
name = "scripts"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "sqe_fitting2",
    "jupytext>=1.19.5",
    "hvplot>=0.12.2", # used for plotting in update-example-datasets
    "jupyter>=1.1.1",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
]

[tool.uv.sources]
sqe_fitting2 = { path = "../", editable = true }
